spring:
  profiles:
    active: secret, dev

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/html/
      suffix: .html

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/

server:
  port: 9600
  servlet:
    context-path: /

# TRACE DEBUG INFO WARN ERROR FATAL OFF
logging:
  level:
#    cn.ultronxr.common: debug
#    cn.ultronxr.valorant.api: debug
#    cn.ultronxr.valorant.bean.VO: debug
#    cn.ultronxr.valorant.bean.mybatis.bean: debug
#    cn.ultronxr.valorant.config: debug
#    cn.ultronxr.valorant.controller: debug
#    cn.ultronxr.valorant.exception: debug
#    cn.ultronxr.valorant.service: debug
#    cn.ultronxr.valorant.util: debug
#    cn.ultronxr.*.bean.mybatis.mapper: debug
    cn.ultronxr.*: info

mybatis-plus:
  type-aliases-package: cn.ultronxr.**.bean.mybatis.bean
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
#      insert-strategy: not_empty
#      update-strategy: not_empty
      # 排除 select 时 Java Bean 属性值为空对 where 筛选条件的影响
      where-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springboot actuator 配置，参见 {@link https://www.cnblogs.com/caoweixiong/p/15325382.html}
management:
  server:
    port: -1
  endpoints:
    # 关闭监控
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        # 开启所有的 endpoints (不包含shutdown)
        include: "*"
        exclude:
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
