spring:
  profiles:
    active: secret, dev

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/html/
      suffix: .html

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/

  redis:
    redisson:
      file: classpath:config/redisson.yml

server:
  port: 9600
  servlet:
    context-path: /

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  type-aliases-package: cn.ultronxr.**.bean.mybatis.bean
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
#      insert-strategy: not_empty
#      update-strategy: not_empty
      # 排除 select 时 Java Bean 属性值为空对 where 筛选条件的影响
      where-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true

# springboot actuator 配置，参见 {@link https://www.cnblogs.com/caoweixiong/p/15325382.html}
management:
  server:
    port: -1
  endpoints:
    # 关闭监控
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        # 开启所有的 endpoints (不包含shutdown)
        include: "*"
        exclude:
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always

valorant:
  datanode:
    # zset 的 redis key ，该 zset 用于维护所有在线的数据节点ID
    redis-zset-key: valorant_datanode_zset
    # redis topic channel 的名称，该 channel 用于主数据节点发布数据更新任务、子数据节点订阅数据更新任务
    # 详细流程：管理员在网页（部署在主数据节点上）点击更新按钮，主数据节点自己开始更新数据的同时向 topic channel 发布更新任务，子数据节点订阅获取到更新任务，也跟着开始更新数据
    redis-topic-channel: valorant_topic_channel
    # 主数据节点的名称
    main-datanode-id: datanode_main
    # 主数据节点的权重（更大的权重会在 zset 中的 rank 递增排名更靠后，revrank 递减排名更靠前）
    main-datanode-score: 999
    # 其他/默认数据节点的权重
    default-datanode-score: 1
    # 定时任务cron：清空datanode、添加datanode
    cron:
      clear-datanode: "0 55 6 * * ? "
      add-datanode: "0 0 7 * * ? "
  storefront:
    # 预更新拳头账号token的数据量（每个数据节点）
    pre-update-account-token:
      count-per-datanode: 660
    # 定时任务cron：事先更新账号token、批量更新每日商店+夜市
    cron:
      pre-update-account-token: "0 8 7 * * ? "
      batch-update-both: "0 0 8 * * ? "

adminAuth:
  cookieName: X-AUTH-TOKEN
  adminPasswordLength: 50
